name: hlint

on:
  push:
  pull_request:

jobs:
  build:
    name: hlint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: haskell/actions/hlint-setup@v2
      name: Set up HLint
      with:
        version: "3.4"

    - uses: haskell/actions/hlint-run@v2
      name: hlint
      with:
        path: '["build", "ghc-corroborate"]'
        fail-on: suggestion